spring:
  application:
    name: backend # Spring Boot uygulama adi
  servlet: # 413 Hata kodunun ve terminaldeki kırmızı yazıların tamamen yok olduğunu göreceksin. O 3 MB'lık fotoğraflar kapıdan rahatça geçecek, AI tarafından kesilecek ve veritabanına 50 KB'lık kuş gibi hafif WebP'ler olarak kaydedilecek!
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  # Veritabani Baglanti Ayarlari
  datasource:
    url: ${DB_URL}  # placeholder
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver  # Çevirmen-> Java kodlarının PostgreSQL anlayacağı dile dönüştürülmesini sağlar
    #Supabase'i boğmamak için bağlantı sınırları koyuyoruz
    hikari:
      maximum-pool-size: 3   # Aynı anda en fazla 3 bağlantı aç
      minimum-idle: 1        # Boştayken sadece 1 bağlantı açık kalsın
      connection-timeout: 20000 # Bağlanamazsa 20 saniye bekle


  # Hibernate / JPA Ayarlari (Tablolari otomatik olusturacak kisim)
  jpa:
    hibernate: # create -> eski tabloları siler ve yepyeni mimarimize göre sıfırdan yaratır.
      ddl-auto: update # update -> Biz Java'da Entity yazinca, gidip veritabaninda tabloyu kendi olusturur
    show-sql: true # Arka planda calısan (SELECT, INSERT, UPDATE)  SQL sorgularini konsolda görmemizi saglar
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true # gereksiz komutları kapat
        prepare_sql: false       
        jdbc:
          batch_size: 20 # Aynı anda 20 kaydı tek pakette gönder
        order_inserts: true # Insert komutlarını optimize et
        order_updates: true # Update komutlarını optimize et
        dialect: org.hibernate.dialect.PostgreSQLDialect # Hibernate'e sorguları oluştururken tam olarak PostgreSQL dilinde yaz.
        format_sql: true # SQL sorguları terminalde gösterir
    open-in-view: false